/// Radio commands
#[derive(Copy, Clone, PartialEq, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Command {
    GetStatus = 0xc0,
    WiteRegister = 0x18,
    ReadRegister = 0x19,
    WriteBuffer = 0x1a,
    ReadBuffer = 0x1b,
    SetSleep = 0x84,
    SetStandby = 0x80,
    SetFs = 0xc1,
    SetTx = 0x83,
    SetRx = 0x82,
    SetRxDutyCycle = 0x94,
    SetCad = 0xc5,
    SetTxContinuousWave = 0xd1,
    SetTxContinuousPreamble = 0xd2,
    SetPacketType = 0x8a,
    GetPacketType = 0x03,
    SetRfFrequency = 0x86,
    SetTxParams = 0x8e,
    SetCadParams = 0x88,
    SetBufferBaseAddress = 0x8f,
    SetModulationParams = 0x8b,
    SetPacketParams = 0x8c,
    GetRxBufferStatus = 0x17,
    GetPacketStatus = 0x1d,
    GetRssiInst = 0x1f,
    SetDioIrqParams = 0x8d,
    GetIrqStatus = 0x15,
    ClearIrqStatus = 0x97,
    Calibrate = 0x89,
    SetRegulatorMode = 0x96,
    SetSaveContext = 0xd5,
    SetAutoTx = 0x98,
    SetAutoFs = 0x9e,
    SetLongPreamble = 0x9b,
    SetAdvancedRanging = 0x9a,
    SetRangingRole = 0xa3,
}
